name: Unit Tests (PR)

on:
  pull_request:
    branches: ['canary', 'master']

jobs:
  test:
    strategy:
      matrix:
        version: [24]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v5

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.version }}
          cache: 'pnpm'

      - run: make test
